# Generated by Django 3.0.5 on 2020-05-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_add_index_task_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='textlogerrormatch', unique_together=None,),
        migrations.RemoveField(model_name='textlogerrormatch', name='classified_failure',),
        migrations.RemoveField(model_name='textlogerrormatch', name='text_log_error',),
        migrations.RemoveField(model_name='textlogerrormetadata', name='best_classification',),
        migrations.RemoveField(model_name='textlogerrormetadata', name='failure_line',),
        migrations.RemoveField(model_name='textlogerrormetadata', name='text_log_error',),
        migrations.RemoveField(model_name='failureline', name='best_classification',),
        migrations.RemoveField(model_name='failureline', name='best_is_verified',),
        migrations.DeleteModel(name='ClassifiedFailure',),
        migrations.DeleteModel(name='TextLogErrorMatch',),
        migrations.DeleteModel(name='TextLogErrorMetadata',),
    ]
